name       : python-engineio
version    : 4.3.1
release    : 2
source     :
    - https://pypi.io/packages/source/p/python-engineio/python-engineio-4.3.1.tar.gz : 6e1d26977ffefe3b7da1b5df7a8750aedc7686da8201cd90daf36693db122489
license    : MIT
component  : programming.python
summary    : Engine.IO server and client for Python
description: |
    Python implementation of the Engine.IO_ realtime client and server.
rundeps    :
    - python-requests
    - python-websocket-client
build      : |
    %python3_setup
install    : |
    %python3_install 
